### ISSUE TITLE
VM image's link has been invalid.

### ISSUE THREAD

**Issue by jams99** [vortexgpgpu/vortex_tutorials#3]
VM image's link has been invalid.
Does anyone know where to find the VM image.

Thank you.

**Comment by xlgforever** [comment]
i am also want to find the VM image, waiting for the problem to be resolved

**Comment by bufans** [comment]
looking for the VM image too

**Comment by jyoung3131** [comment]
This should be updated - there is a limitation on Box in terms of how long it will let us share files so we have to update it every now and then..
