### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by JacobLevinson** [vortexgpgpu/vortex_tutorials#7]
In the VM_Imgs/VM_README.md there is an issue:

In step 2 of setup it says:

# We create a new local VM image from the vortex-ubuntu.box file and 
# then initialize a Vagrantfile with `vagrant init`

vagrant box add vortex-ubuntu.box --name vortex-micro55
vagrant init vortex-micro56

Clearly the name being micro55 and the init being micro56 do not match, so this will not work.

**Comment by lpc97667** [comment]
Fixed now, thank you.
